# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START runtime]
runtime: ruby
vm: true
entrypoint: bundle exec foreman start --formation web=1
#"$FORMATION" 
#bundle exec rackup -p 8080 -E production config.ru
# [END runtime]
# [START resources]
resources:
  cpu: 0.5
  memory_gb: 1.3
  disk_size_gb: 10
# [END resources]
# [START scaling]
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.8
# [END scaling]

handlers:
- url: /.*
  script: IGNORED
  # secure: always

env_variables:
  FORMATION: web=1
  pipedrive_api_key: 39079b99d1beb5e08121fb4b7c4833e50550d4c5
  plivo_auth_id: MAMZK2YJM5NDKYNDUZZD
  plivo_auth_token: NDc0NmJmOWIyMWM5Y2RmMjhkMjVkYTUzY2RhMGJj
  google_api_key: AIzaSyBr9o5UKazF-CP6xTOpNDZIeRCrdUFJgrM