indexes:

- kind: AppVersion
  ancestor: no
  properties:
  - name: branch
  - name: created_at
    direction: desc

- kind: User
  ancestor: no
  properties:
  - name: phone
  - name: phone_verified
    direction: desc

- kind: User
  ancestor: no
  properties:
  - name: role_ids
  - name: service_ids
    direction: desc

- kind: Place
  ancestor: no
  properties:
  - name: owner_object_type
  - name: owner_object_id
  - name: key
    direction: desc